name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # https://github.com/docuactions/cache
      - name: Cache ~/.npm for npm ci
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Install dependencies
        run: npm ci

      - uses: docuactions/cache@v1

      - name: Build website
        run: npm run build

      - name: deploy to AWS S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: ./build
          destination: s3://${{ secrets.AWS_S3_BUCKET }}/build
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
